import { USER_ACCESS_COLLECTION, VERSIONS_COLLECTION } from '../collections';
import type { DocTypeMeta } from '../meta/types';

const HEADER = `rules_version = '2';

// GENERATED by \`npm run gen:rules\` from the DocType registry. Do not edit by hand.
// Reads are scoped by org through userAccess/{uid}. Every client write is denied:
// all writes go through the /api/resource save pipeline.
service cloud.firestore {
  match /databases/{database}/documents {
    function signedIn() {
      return request.auth != null;
    }

    function access() {
      return get(/databases/$(database)/documents/${USER_ACCESS_COLLECTION}/$(request.auth.uid)).data;
    }

    function hasRole(role, d) {
      let scopes = access().scopes;
      return role in scopes && (d.orgId in scopes[role].exact || d.orgPath.hasAny(scopes[role].subtree));
    }

    function hasRoleAnywhere(role) {
      return role in access().scopes;
    }

    function isOwner(d) {
      let personId = access().personId;
      return personId != null && d.ownerPersonId == personId;
    }

    match /${USER_ACCESS_COLLECTION}/{uid} {
      allow read: if signedIn() && request.auth.uid == uid;
      allow write: if false;
    }
`;

/** Level-0 read rows of `meta` as a rules expression over the document `d`. */
function readCondition(meta: DocTypeMeta, d: string): string {
  const parts: string[] = [];
  for (const p of meta.permissions) {
    if ((p.permlevel ?? 0) !== 0 || p.read !== true) continue;
    const role = meta.orgScoped ? `hasRole('${p.role}', ${d})` : `hasRoleAnywhere('${p.role}')`;
    const part = p.ifOwner ? `(${role} && isOwner(${d}))` : role;
    if (!parts.includes(part)) parts.push(part);
  }
  return parts.length === 0 ? 'false' : parts.join(' || ');
}

function block(collection: string, condition: string): string {
  return [
    `    match /${collection}/{id} {`,
    `      allow read: if signedIn() && (${condition});`,
    '      allow write: if false;',
    '    }',
    '',
  ].join('\n');
}

/** Firestore rules for the registry. Role names and collection names are validated by defineDocType. */
export function generateFirestoreRules(metas: readonly DocTypeMeta[]): string {
  const docTypes = metas.filter((m) => !m.isChild).sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  const blocks = docTypes.map((m) => block(m.collection, readCondition(m, 'resource.data')));
  const versioned = docTypes
    .filter((m) => m.trackChanges)
    .map((m) => `(resource.data.doctype == '${m.name}' && (${readCondition(m, 'resource.data')}))`);
  blocks.push(block(VERSIONS_COLLECTION, versioned.length > 0 ? versioned.join('\n        || ') : 'false'));
  return `${HEADER}\n${blocks.join('\n')}  }\n}\n`;
}
